# Generated by Django 4.2.7 on 2023-12-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mail', models.IntegerField(max_length=40)),
                ('feedback', models.CharField(max_length=400)),
            ],
        ),
    ]
