# Generated by Django 4.2.7 on 2023-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mail',
            field=models.CharField(max_length=40),
        ),
    ]
